version: "3.8"

services:
  podible:
    build:
      context: .
      args:
        GIT_SHA: ${GIT_SHA:-}
        GIT_COMMIT_MESSAGE: ${GIT_COMMIT_MESSAGE:-}
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./books:/books:ro
      - ./data:/config
    environment:
      - PORT=80
    command: ["bun", "run", "server.ts", "/books"]
